### PR TITLE
Svelte: Generate docgen

### LINKED ISSUE #390: [Bug] Documentation is not generated for Svelte components
### What version of `vite` are you using?

n/a

### System info and storybook versions

n/a

### Describe the Bug

Currently we only support react and vue3 for docgen.  We should convert https://github.com/storybookjs/storybook/blob/c0401cbd3225340ff7f2e633868689a68538f84d/app/svelte/src/server/svelte-docgen-loader.ts#L44 into a vite plugin so that we can support svelte as well.

### Link to Minimal Reproducible Example

_No response_

### Participation

- [X] I am willing to submit a pull request for this issue.

### PR DESCRIPTION
**Pull request by j3rem1e**
Fix #390

### CODE REVIEW

File: packages/builder-vite/plugins/svelte-docgen.ts [hunk 1]
```diff
@@ -0,0 +1,97 @@
...
+
+  return {
+    name: 'svelte-docgen',
+    async transform(src: string, id: string) {
+      if (/\.(svelte)$/.test(id)) {
+        const resource = path.relative(cwd, id);
+
+        let docOptions;
+        if (preprocessOptions) {
+          const src = fs.readFileSync(resource).toString();
```
Comment (joshwooding) [inline packages/builder-vite/plugins/svelte-docgen.ts:56]: Any reason to prefer sync here?

**Review by joshwooding — APPROVED** [review]
